### PR TITLE
Revert "Added user dirs"

### PR DESCRIPTION
**Pull request by mschenk42**
Reverts git-time-metric/gtm-jetbrains-plugin#3

### CODE REVIEW

**Comment by dnedrow** [comment]
Hi, Michael.

Was there a problem with my commit? I can live with building a custom plugin so I can use it. 

I've been thinking it might be better to provide a GUI for settings that would allow the user to select their gtm executable. A number of plugins work this way.

What do you think?

**Comment by mschenk42** [comment]
I thought there may have been based on some user feedback.  Now I'm doubting that it was problematic.  I may just re-apply and release the changes for the plugin.

Has everything been working OK for you in Windows?  There are a couple people experiencing poor performance on Windows.  One is using the JetBrains plugin and the other uses the Sublime plugin.

**Comment by dnedrow** [comment]
@mschenk42 I don't use Windows, so I can't say in re: performance on that platform. I know on Mac and Red Hat I haven't had any issues.

I don't think anything I did would impact performance. The only thing that should happen is that the stand user specific bin dirs are searched for GTM.

If you feel comfortable doing it, can you re-integrate the PR? I'd be glad to help keep an eye on it.

If you like, I can submit a new PR.

**Comment by mschenk42** [comment]
Hi @dnedrow I reverted the revert ;). Can you please review this to make sure I didn't miss anything https://github.com/git-time-metric/gtm-jetbrains-plugin/commit/d1c7af1a63a3fe093e182f5dc21fdb674502cb24.

**Comment by dnedrow** [comment]
@mschenk42 , I pulled the most recent update, compiled and installed it. Everything seams to be working fine in IDEA and AppCode. I'd say let it loose. ;)

**Comment by mschenk42** [comment]
@dnedrow thanks for the testing, I'll recompile and publish the plugin this weekend.

**Comment by mschenk42** [comment]
@dnedrow published the plugin in JetBrains Plugin repo.  Let me know if you have any issues downloading the latest.

**Pull request merged**
